version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: saas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: saas_db
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: saas_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - saas_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://saas_user:saas_password@mysql:3306/saas_db
      NODE_ENV: production
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
    networks:
      - saas_network

volumes:
  mysql_data:

networks:
  saas_network:
    driver: bridge